<a href="https://colab.research.google.com/github/newstage75/python_data_analysis_100knock/blob/main/%E7%AC%AC2%E7%AB%A0/%E5%B0%8F%E5%A3%B2%E5%BA%97%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%81%A7%E3%83%87%E3%83%BC%E3%82%BF%E5%8A%A0%E5%B7%A5%E3%82%92%E8%A1%8C%E3%81%8610%E6%9C%AC%E3%83%8E%E3%83%83%E3%82%AF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Google Driveと接続を行います。これを行うことで、Driveにあるデータにアクセスできるようになります。
# 下記セルを実行すると、Googleアカウントのログインを求められますのでログインしてください。
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# 作業フォルダへの移動を行います。
# 人によって作業場所が異なるので、その場合作業場所を変更してください。
import os
os.chdir('/content/drive/MyDrive/データサイエンス/20240505python実践データ分析100本ノック/100knock-data_analytics/2章')

In [3]:
import pandas as pd
uriage_data = pd.read_csv("uriage.csv")
uriage_data.head()

         purchase_date item_name  item_price customer_name
0  2019-06-13 18:02:34       商品A       100.0         深井菜々美
1  2019-07-13 13:05:29     商 品 S         NaN          浅田賢二
2  2019-05-11 19:42:07     商 品 a         NaN          南部慶二
3  2019-02-12 23:40:45       商品Z      2600.0          麻生莉緒
4  2019-04-22 03:09:35       商品a         NaN          平田鉄二

In [31]:
kokyaku_data = pd.read_excel("kokyaku_daicho.xlsx")
kokyaku_data.head(10)

       顧客名        かな  地域                      メールアドレス         登録日
0    須賀ひとみ    すが ひとみ  H市      suga_hitomi@example.com  2018/01/04
1   岡田　 敏也   おかだ としや  E市    okada_toshiya@example.com       42782
2     芳賀 希    はが のぞみ  A市      haga_nozomi@example.com  2018/01/07
3    荻野  愛    おぎの あい  F市         ogino_ai@example.com       42872
4    栗田 憲一  くりた けんいち  E市   kurita_kenichi@example.com       43127
5    梅沢 麻緒   うめざわ まお  A市      umezawa_mao@example.com  2017/06/20
6   相原 ひとり  あいはら ひとり  H市    aihara_hitori@example.com  2018/06/11
7    新村 丈史  にいむら たけし  B市  niimura_takeshi@example.com  2017/05/19
8  石川  まさみ  いしかわ まさみ  G市  ishikawa_masami@example.com  2018/02/12
9    小栗 正義  おぐり まさよし  G市  oguri_masayoshi@example.com  2017/07/05

In [5]:
uriage_data["item_name"].head()

0      商品A
1    商 品 S
2    商 品 a
3      商品Z
4      商品a
Name: item_name, dtype: object

In [6]:
uriage_data["item_price"].head()

0     100.0
1       NaN
2       NaN
3    2600.0
4       NaN
Name: item_price, dtype: float64

In [7]:
# 中身の確認（日付別）
uriage_data["purchase_date"] = pd.to_datetime(uriage_data["purchase_date"])
uriage_data["purchase_date"].head()

0   2019-06-13 18:02:34
1   2019-07-13 13:05:29
2   2019-05-11 19:42:07
3   2019-02-12 23:40:45
4   2019-04-22 03:09:35
Name: purchase_date, dtype: datetime64[ns]

In [8]:
# 日付を年月の形に変換（列が追加されている。）
# 集計単位に合わせて日付を変換する処理は実際かなり行われる。
uriage_data["purchase_month"] = uriage_data["purchase_date"].dt.strftime("%Y%m")
uriage_data.head()

        purchase_date item_name  item_price customer_name purchase_month
0 2019-06-13 18:02:34       商品A       100.0         深井菜々美         201906
1 2019-07-13 13:05:29     商 品 S         NaN          浅田賢二         201907
2 2019-05-11 19:42:07     商 品 a         NaN          南部慶二         201905
3 2019-02-12 23:40:45       商品Z      2600.0          麻生莉緒         201902
4 2019-04-22 03:09:35       商品a         NaN          平田鉄二         201904

In [9]:
# 「売上履歴」から商品ごとの月売上合計を集計
#　縦軸に「購入年月日（purchase_month）」、横軸に「商品（item_name）」
res = uriage_data.pivot_table(index="purchase_month", columns="item_name", aggfunc="size", fill_value=0)
res

item_name,商品W,商 品 n,商品E,商品M,商品P,商品S,商品W,商品X,商 品O,商 品Q,...,商品k,商品l,商品o,商品p,商品r,商品s,商品t,商品v,商品x,商品y
purchase_month,,,,,,,,,,,,,,,,,,,,,
201901,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
201902,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
201903,0,0,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
201904,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
201905,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
201906,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
201907,0,0,0,0,0,0,0,0,1,0,...,0,0,1,0,2,0,0,0,0,0

In [10]:
# values="item_price", aggfunc="sum"で売上を集計している。
res = uriage_data.pivot_table(index="purchase_month", columns="item_name", values="item_price", aggfunc="sum", fill_value=0)
res

item_name,商品W,商 品 n,商品E,商品M,商品P,商品S,商品W,商品X,商 品O,商 品Q,...,商品k,商品l,商品o,商品p,商品r,商品s,商品t,商品v,商品x,商品y
purchase_month,,,,,,,,,,,,,,,,,,,,,
201901,0.0,1400.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1100.0,1200.0,1500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
201902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2400.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1900.0,2000.0,2200.0,0.0,0.0
201903,0.0,0.0,500.0,1300.0,1600.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
201904,2300.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1700.0,...,0.0,0.0,0.0,0.0,0.0,1900.0,0.0,0.0,0.0,0.0
201905,0.0,0.0,0.0,0.0,0.0,1900.0,0.0,0.0,0.0,0.0,...,0.0,1200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2500.0
201906,0.0,0.0,0.0,0.0,0.0,0.0,2300.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1600.0,0.0,0.0,0.0,0.0,2400.0,0.0
201907,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1500.0,0.0,1800.0,0.0,0.0,0.0,0.0,0.0

In [11]:
#　商品名のユニーク数の確認
print(len(pd.unique(uriage_data["item_name"])))

99

In [12]:
uriage_data["item_name"] = uriage_data["item_name"].str.upper()
uriage_data["item_name"] = uriage_data["item_name"].str.replace("　", "")
uriage_data["item_name"] = uriage_data["item_name"].str.replace(" ", "")
uriage_data.sort_values(by=["item_name"], ascending=True)

           purchase_date item_name  item_price customer_name purchase_month
0    2019-06-13 18:02:34       商品A       100.0         深井菜々美         201906
1748 2019-05-19 20:22:22       商品A       100.0          松川綾女         201905
223  2019-06-25 08:13:20       商品A       100.0           板橋隆         201906
1742 2019-06-13 16:03:17       商品A       100.0          小平陽子         201906
1738 2019-02-10 00:28:43       商品A       100.0          松田浩正         201902
...                  ...       ...         ...           ...            ...
2880 2019-04-22 00:36:52       商品Y         NaN          田辺光洋         201904
2881 2019-04-30 14:21:09       商品Y         NaN          高原充則         201904
1525 2019-01-24 10:27:23       商品Y      2500.0         五十嵐春樹         201901
1361 2019-05-28 13:45:32       商品Y      2500.0         大崎ヒカル         201905
3    2019-02-12 23:40:45       商品Z      2600.0          麻生莉緒         201902

[2999 rows x 5 columns]

In [14]:
print(pd.unique(uriage_data["item_name"]))
print(len(pd.unique(uriage_data["item_name"])))

['商品A' '商品S' '商品Z' '商品V' '商品O' '商品U' '商品L' '商品C' '商品I' '商品R' '商品X' '商品G'
 '商品P' '商品Q' '商品Y' '商品N' '商品W' '商品E' '商品K' '商品B' '商品F' '商品D' '商品M' '商品H'
 '商品T' '商品J']
26

In [15]:
# 欠損値のチェック
uriage_data.isnull().any(axis=0)

purchase_date     False
item_name         False
item_price         True
customer_name     False
purchase_month    False
dtype: bool

In [16]:
# .any(axis=0)をつけることで、列ごとの欠損値をつけることができている。
uriage_data.isnull()

      purchase_date  item_name  item_price  customer_name  purchase_month
0             False      False       False          False           False
1             False      False        True          False           False
2             False      False        True          False           False
3             False      False       False          False           False
4             False      False        True          False           False
...             ...        ...         ...            ...             ...
2994          False      False       False          False           False
2995          False      False       False          False           False
2996          False      False        True          False           False
2997          False      False        True          False           False
2998          False      False       False          False           False

[2999 rows x 5 columns]

In [17]:
#item_priceの中で欠損値がある箇所を特定
flg_is_null = uriage_data["item_price"].isnull()
print(flg_is_null)

0       False
1        True
2        True
3       False
4        True
        ...
2994    False
2995    False
2996     True
2997     True
2998    False
Name: item_price, Length: 2999, dtype: bool

In [18]:
#ループ処理を行い、データが欠損している商品の一覧を作成する処理。
# .loc関数は条件を付与し、それに合致するものを抽出（今回は金額にnullが存在する商品名）
for trg in list(uriage_data.loc[flg_is_null, "item_name"].unique()):
  price = uriage_data.loc[(~flg_is_null) & (uriage_data["item_name"] == trg), "item_price"].max()
  uriage_data.loc[(flg_is_null) & (uriage_data["item_name"]==trg), "item_price"] = price
uriage_data.head()

        purchase_date item_name  item_price customer_name purchase_month
0 2019-06-13 18:02:34       商品A       100.0         深井菜々美         201906
1 2019-07-13 13:05:29       商品S      1900.0          浅田賢二         201907
2 2019-05-11 19:42:07       商品A       100.0          南部慶二         201905
3 2019-02-12 23:40:45       商品Z      2600.0          麻生莉緒         201902
4 2019-04-22 03:09:35       商品A       100.0          平田鉄二         201904

In [19]:
uriage_data.isnull().any(axis=0)

purchase_date     False
item_name         False
item_price        False
customer_name     False
purchase_month    False
dtype: bool

In [20]:
# 各商品の最大値・最小値を求めることで、データが問題ないか確認する
# 最後の「skipna=False」 はNaNデータを無視するかどうか。Falseは無視しないため、存在する場合は最小額がNaNになる。
for trg in list(uriage_data["item_name"].sort_values().unique()):
  print(trg + "の最大額：" + str(uriage_data.loc[uriage_data["item_name"]==trg]["item_price"].max()) + "の最小額：" + str(uriage_data.loc[uriage_data["item_name"]==trg]["item_price"].min(skipna=False)))

商品Aの最大額：100.0の最小額：100.0
商品Bの最大額：200.0の最小額：200.0
商品Cの最大額：300.0の最小額：300.0
商品Dの最大額：400.0の最小額：400.0
商品Eの最大額：500.0の最小額：500.0
商品Fの最大額：600.0の最小額：600.0
商品Gの最大額：700.0の最小額：700.0
商品Hの最大額：800.0の最小額：800.0
商品Iの最大額：900.0の最小額：900.0
商品Jの最大額：1000.0の最小額：1000.0
商品Kの最大額：1100.0の最小額：1100.0
商品Lの最大額：1200.0の最小額：1200.0
商品Mの最大額：1300.0の最小額：1300.0
商品Nの最大額：1400.0の最小額：1400.0
商品Oの最大額：1500.0の最小額：1500.0
商品Pの最大額：1600.0の最小額：1600.0
商品Qの最大額：1700.0の最小額：1700.0
商品Rの最大額：1800.0の最小額：1800.0
商品Sの最大額：1900.0の最小額：1900.0
商品Tの最大額：2000.0の最小額：2000.0
商品Uの最大額：2100.0の最小額：2100.0
商品Vの最大額：2200.0の最小額：2200.0
商品Wの最大額：2300.0の最小額：2300.0
商品Xの最大額：2400.0の最小額：2400.0
商品Yの最大額：2500.0の最小額：2500.0
商品Zの最大額：2600.0の最小額：2600.0

## ノック16:顧客名の揺れを修正

In [21]:
# 顧客台帳のデータの揺れを確認
kokyaku_data["顧客名"].head()

0     須賀ひとみ
1    岡田　 敏也
2      芳賀 希
3     荻野  愛
4     栗田 憲一
Name: 顧客名, dtype: object

In [23]:
# 売上データの顧客名
uriage_data["customer_name"].head()

0    深井菜々美
1     浅田賢二
2     南部慶二
3     麻生莉緒
4     平田鉄二
Name: customer_name, dtype: object

In [26]:
print(kokyaku_data["顧客名"].unique())
print(len(kokyaku_data["顧客名"].unique()))

['須賀ひとみ' '岡田\u3000 敏也' '芳賀 希' '荻野  愛' '栗田 憲一' '梅沢 麻緒' '相原 ひとり' '新村 丈史'
 '石川  まさみ' '小栗 正義' '大倉 晃司' '那須 蒼甫' '清水 裕次郎' '榊原 しぼり' '高沢   美咲' '川島 友以乃'
 '唐沢 景子' '稲田 将也' '秋葉 あき' '西脇 礼子' '内村 まさみ' '進藤 瞬' '小口 豊' '笹原 しぼり' '岩佐 孝太郎'
 '河村 由樹' '菅原 誠治' '榎本 薫' '高梨 結衣' '鶴岡 薫' '藤木 一恵' '森岡 季衣' '田畑 正敏' '宇野 秀樹'
 '高原 充則' '梅村 秀樹' '浅田 賢二' '石渡 小雁' '吉岡 サダヲ' '井口 寛治' '奥 光洋' '佐藤 慶二' '東 光博'
 '高田 さんま' '合田 光' '深田 信輔' '島 英嗣' '梅津 淳子' '日比野 徹' '熊倉 綾' '松田  浩正' '楠 高史'
 '岡 慶太' '市田 寿明' '山西 花' '青山 鉄洋' '松川 綾女' '大滝 麗奈' '赤木 愛梨' '楠  哲平' '堀内 聡'
 '八木 雅彦' '林 勇' '日野 夏希' '麻生 莉緒' '根岸 仁晶' '赤木 だん吉' '亀井 一徳' '横田 遥' '野本 仁晶'
 '西原 未華子' '五十嵐 春樹' '堀江 佑' '久保田 倫子' '金森 なつみ' '城戸 芳正' '望月 真悠子' '井本 マサカズ'
 '米沢 仁晶' '本橋 直人' '古川 信吾' '岩沢 那奈' '西島 知世' '戸塚 美幸' '深井 照生' '新谷 智花' '有馬 徹平'
 '本多 フミヤ' '浜田 未華子' '牧田 玲那' '島 孝太郎' '石田 花' '星野 美嘉' '黒谷 長利' '深沢 ひろ子' '矢部 夏空'
 '立石 茜' '手塚 雅之' '松谷 愛子' '中田 美智子' '片瀬 長利' '石崎 幸子' '明石家 明' '小川 美菜' '田辺 光洋'
 '神原 美嘉' '岩城 徹平' '相川 良介' '植村 遥' '井川 真悠子' '松元 翔太' 'さだ 千佳子' '島本 研二' '影山 輝信'
 '浅見 広司' '石野 仁' '小平 陽子' '福本 美幸' '中 仁晶' '田辺 きみまろ' '熊倉 明日' '鈴木 一哉' '杉田 将也'
 '徳重 優' '松岡 ノブヒコ' '藤 広之' '谷本 愛梨' '松沢 育二' '清水 佑' '土屋 朝陽' '鳥居 広司' '福島 友也'
 '堀 サンタマリア' '井川 里穂' '田崎 菜々美' '平田 鉄二' '井上 桃子' '尾形 小雁' '沖 遥' '矢部 美幸'
 '島袋 友以乃' '深井 菜々美' '南部 慶二' '若杉 徹' '矢部 惇' '熊井 憲史' '岡村 希' '桑原 桃子' '原口 俊二'
 '尾上 勝久' '杉下 悟志' '志村 サダヲ' '山口 法子' '大城 ケンイチ' '新村 美月' '河内 さとみ' '内田 聡'
 '吉村 愛梨' '根岸 莉央' '丸山 光臣' '石田 佑' '根本 博明' '今 茜' '村山 知世' '大山 咲' '島崎 礼子'
 '松居 満' '田上 美佐子' '篠山 雅功' '外山 広司' '岩井 \u3000莉緒' '大崎 ヒカル' '矢沢 恵梨香' '石田  郁恵'
 '荻野 愛菜' '香椎 優一' '黄川田 博之' '井村 俊二' '植木 沙知絵' '小松 隼士' '松村 聡' '平賀 一哉' '手塚 進'
 '磯野 希' '白井 俊二' '笹川 照生' '芦田 博之' '大地 礼子' '小町 瞬' '水野 メイサ' '板橋 隆' '綾瀬 俊介'
 '和泉 直人' '堀北 雅彦' '唐沢 涼' '川上 りえ' '小松 季衣' '白鳥 りえ' '大西 隆之介' '福井 美希']
200

In [27]:
kokyaku_data["顧客名"] = kokyaku_data["顧客名"].str.replace("　", "")
kokyaku_data["顧客名"] = kokyaku_data["顧客名"].str.replace(" ", "")
kokyaku_data["顧客名"].head()

0    須賀ひとみ
1     岡田敏也
2      芳賀希
3      荻野愛
4     栗田憲一
Name: 顧客名, dtype: object

In [28]:
print(kokyaku_data["顧客名"].unique())
print(len(kokyaku_data["顧客名"].unique()))

['須賀ひとみ' '岡田敏也' '芳賀希' '荻野愛' '栗田憲一' '梅沢麻緒' '相原ひとり' '新村丈史' '石川まさみ' '小栗正義'
 '大倉晃司' '那須蒼甫' '清水裕次郎' '榊原しぼり' '高沢美咲' '川島友以乃' '唐沢景子' '稲田将也' '秋葉あき' '西脇礼子'
 '内村まさみ' '進藤瞬' '小口豊' '笹原しぼり' '岩佐孝太郎' '河村由樹' '菅原誠治' '榎本薫' '高梨結衣' '鶴岡薫'
 '藤木一恵' '森岡季衣' '田畑正敏' '宇野秀樹' '高原充則' '梅村秀樹' '浅田賢二' '石渡小雁' '吉岡サダヲ' '井口寛治'
 '奥光洋' '佐藤慶二' '東光博' '高田さんま' '合田光' '深田信輔' '島英嗣' '梅津淳子' '日比野徹' '熊倉綾' '松田浩正'
 '楠高史' '岡慶太' '市田寿明' '山西花' '青山鉄洋' '松川綾女' '大滝麗奈' '赤木愛梨' '楠哲平' '堀内聡' '八木雅彦'
 '林勇' '日野夏希' '麻生莉緒' '根岸仁晶' '赤木だん吉' '亀井一徳' '横田遥' '野本仁晶' '西原未華子' '五十嵐春樹'
 '堀江佑' '久保田倫子' '金森なつみ' '城戸芳正' '望月真悠子' '井本マサカズ' '米沢仁晶' '本橋直人' '古川信吾' '岩沢那奈'
 '西島知世' '戸塚美幸' '深井照生' '新谷智花' '有馬徹平' '本多フミヤ' '浜田未華子' '牧田玲那' '島孝太郎' '石田花'
 '星野美嘉' '黒谷長利' '深沢ひろ子' '矢部夏空' '立石茜' '手塚雅之' '松谷愛子' '中田美智子' '片瀬長利' '石崎幸子'
 '明石家明' '小川美菜' '田辺光洋' '神原美嘉' '岩城徹平' '相川良介' '植村遥' '井川真悠子' '松元翔太' 'さだ千佳子'
 '島本研二' '影山輝信' '浅見広司' '石野仁' '小平陽子' '福本美幸' '中仁晶' '田辺きみまろ' '熊倉明日' '鈴木一哉'
 '杉田将也' '徳重優' '松岡ノブヒコ' '藤広之' '谷本愛梨' '松沢育二' '清水佑' '土屋朝陽' '鳥居広司' '福島友也'
 '堀サンタマリア' '井川里穂' '田崎菜々美' '平田鉄二' '井上桃子' '尾形小雁' '沖遥' '矢部美幸' '島袋友以乃' '深井菜々美'
 '南部慶二' '若杉徹' '矢部惇' '熊井憲史' '岡村希' '桑原桃子' '原口俊二' '尾上勝久' '杉下悟志' '志村サダヲ'
 '山口法子' '大城ケンイチ' '新村美月' '河内さとみ' '内田聡' '吉村愛梨' '根岸莉央' '丸山光臣' '石田佑' '根本博明'
 '今茜' '村山知世' '大山咲' '島崎礼子' '松居満' '田上美佐子' '篠山雅功' '外山広司' '岩井莉緒' '大崎ヒカル'
 '矢沢恵梨香' '石田郁恵' '荻野愛菜' '香椎優一' '黄川田博之' '井村俊二' '植木沙知絵' '小松隼士' '松村聡' '平賀一哉'
 '手塚進' '磯野希' '白井俊二' '笹川照生' '芦田博之' '大地礼子' '小町瞬' '水野メイサ' '板橋隆' '綾瀬俊介' '和泉直人'
 '堀北雅彦' '唐沢涼' '川上りえ' '小松季衣' '白鳥りえ' '大西隆之介' '福井美希']
200

## ノック17:日付の揺れを修正

In [29]:
flg_is_serial = kokyaku_data["登録日"].astype("str").str.isdigit()
flg_is_serial.sum()

22

In [30]:
formSerial = pd.to_timedelta(kokyaku_data.loc[flg_is_serial, "登録日"].astype("float") - 2, unit="D") + pd.to_datetime("1900/01/01")
formSerial

1     2017-02-16
3     2017-05-17
4     2018-01-27
21    2017-07-04
27    2017-06-15
47    2017-01-06
49    2017-07-13
53    2017-04-08
76    2018-03-29
80    2018-01-10
99    2017-05-30
114   2018-06-03
118   2018-01-29
122   2018-04-16
139   2017-05-25
143   2017-03-24
155   2017-01-19
172   2018-03-22
179   2017-01-08
183   2017-07-24
186   2018-07-13
192   2018-06-08
Name: 登録日, dtype: datetime64[ns]

In [33]:
formString = pd.to_datetime(kokyaku_data.loc[~flg_is_serial, "登録日"])
formString

0     2018-01-04
2     2018-01-07
5     2017-06-20
6     2018-06-11
7     2017-05-19
         ...
195   2017-06-20
196   2018-06-20
197   2017-04-29
198   2019-04-19
199   2019-04-23
Name: 登録日, Length: 178, dtype: datetime64[ns]

In [36]:
formSerial.head()

1    2017-02-16
3    2017-05-17
4    2018-01-27
21   2017-07-04
27   2017-06-15
Name: 登録日, dtype: datetime64[ns]

In [37]:
formString.head()

0   2018-01-04
2   2018-01-07
5   2017-06-20
6   2018-06-11
7   2017-05-19
Name: 登録日, dtype: datetime64[ns]

In [38]:
# formSerialとformStringを結合し、登録日に代入
kokyaku_data["登録日"] = pd.concat([formSerial, formString])
kokyaku_data

        顧客名           かな  地域                         メールアドレス        登録日
0     須賀ひとみ       すが ひとみ  H市         suga_hitomi@example.com 2018-01-04
1    岡田　 敏也      おかだ としや  E市       okada_toshiya@example.com 2017-02-16
2      芳賀 希       はが のぞみ  A市         haga_nozomi@example.com 2018-01-07
3     荻野  愛       おぎの あい  F市            ogino_ai@example.com 2017-05-17
4     栗田 憲一     くりた けんいち  E市      kurita_kenichi@example.com 2018-01-27
..      ...          ...  ..                             ...        ...
195   川上 りえ      かわかみ りえ  G市        kawakami_rie@example.com 2017-06-20
196   小松 季衣      こまつ としえ  E市      komatsu_toshie@example.com 2018-06-20
197   白鳥 りえ      しらとり りえ  F市       shiratori_rie@example.com 2017-04-29
198  大西 隆之介  おおにし りゅうのすけ  H市  oonishi_ryuunosuke@example.com 2019-04-19
199   福井 美希       ふくい みき  D市         fukui_miki1@example.com 2019-04-23

[200 rows x 5 columns]

In [39]:
# 登録日から登録月を算出し、集計
kokyaku_data["登録年月"] = kokyaku_data["登録日"].dt.strftime("%Y%m")
rslt = kokyaku_data.groupby("登録年月").count()["顧客名"]
print(rslt) # rsltはresultからきてる。
print(len(kokyaku_data))

登録年月
201701    15
201702    11
201703    14
201704    15
201705    14
201706    13
201707    17
201801    13
201802    15
201803    17
201804     5
201805    19
201806    13
201807    17
201904     2
Name: 顧客名, dtype: int64
200

In [40]:
flg_is_serial = kokyaku_data["登録日"].astype("str").str.isdigit()
flg_is_serial.sum()

0